# -*- coding: utf-8 -*-
"""Desserting_Remove Emoji.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AkYQ2sgnqw4BxyJXHzXF8ZxcrDCihuE5
"""

import pandas as pd
import re 
import math

# csv 파일 읽어오기
raw_data = pd.read_csv('Instagram Crawling.csv', encoding='utf-8').drop('Unnamed: 0', axis=1)

raw_data.head()

# emoji를 지우는 함수

def remove_emoji(string):
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               u"\U00002500-\U00002BEF"  # chinese char
                               u"\U00002702-\U000027B0"
                               u"\U00002702-\U000027B0"
                               u"\U0001f926-\U0001f937"
                               u"\U00010000-\U0010ffff"
                               u"\u2640-\u2642"
                               u"\u2600-\u2B55"
                               u"\u200d"
                               u"\u23cf"
                               u"\u23e9"
                               u"\u231a"
                               u"\ufe0f"  # dingbats
                               u"\u3030"
                               "]+", flags=re.UNICODE)
    
    return emoji_pattern.sub(r'', string)

# Review와 Hashtag에 적용

for i in range(len(raw_data)):
    raw_data['Review'][i] = remove_emoji(str(raw_data['Review'][i]))
    raw_data['Hashtag'][i] = remove_emoji(str(raw_data['Hashtag'][i]))

raw_data.head()

# Hashtag의 #을 지우는 코드

for i in range(len(raw_data)):
    if raw_data['Hashtag'][i] == "nan": # Hashtag가 아무것도 없을 경우
        raw_data['Hashtag'][i] = None   # None으로 변경
    else:
        raw_data['Hashtag'][i] = raw_data.Hashtag[i][1:].replace("#",",")

raw_data.head()

raw_data.to_csv("Remove Emoji.csv", encoding="utf-8")