# -*- coding: utf-8 -*-
"""메뉴 사전 생성 v0.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PmU9Dl5witYsphJWrOK4xbXH8L4z5osG
"""

!git clone https://github.com/kakao/khaiii.git
!pip install cmake

!mkdir build

!cd build && cmake /content/khaiii

!cd /content/build/ && make all

!cd /content/build/ && make resource

!cd /content/build && make install

!cd /content/build && make package_python

!pip install /content/build/package_python

"""# 메뉴 가져오기
3개의 엑셀 파일에서 메뉴를 가져와 ㄱ-ㅎ, a-z 사전에 입력
"""

import pandas as pd
import re 
import math
from unicodedata import normalize
import re
import openpyxl

# 한글 자모분리 모듈
!pip install jamo
from jamo import h2j, j2hcj

j2hcj(h2j('ccc'))[0]

kr='ㄱㄴㄷㄹㅁㅂㅅㅇㅈㅊㅋㅌㅍㅎㄲㄸㅉㅃㅆ'
en='abcdefghijknmlopqrstuvwxyz'
kr_list = [i for i in kr]
en_list = [i for i in en]
all_list = kr_list+en_list

is_kr = re.compile('[^가-힣]')
is_en = re.compile('[-a-zA-Z]')
is_num = re.compile('[0-9]')

dessert_name_dic = {}
for i in all_list:
  dessert_name_dic[i]=[]

want = [300,600,900]

for i in want:
  work_file = openpyxl.load_workbook('blogMenuInfo_{}.xlsx'.format(i))
  work_file_sheet = work_file.get_sheet_by_name('아뜰리에_메뉴')
  row_len = work_file_sheet.max_row
  for ii in range(2, row_len+1):
    item = re.sub('[^\w\s]','',work_file_sheet['b{}'.format(ii)].value)
    
    if len(is_en.findall(item)) != 0:    #영어 메뉴인지 확인하고, 소문자로 변경
      item = item.lower()
    if len(is_num.findall(item[0])) != 0: #숫자 메뉴인지 확인하고, 숫자 삭제
      item = re.sub('[0-9]','',item)
    

    first_c = j2hcj(h2j(item))[0]           #자모분리하여 첫번째 단어 = 딕셔너리 키
    try:
      dessert_name_dic[first_c].append(item)
      if len(item.split()) >=2:               #띄어쓰기가 있는 메뉴 이름은 스플릿하여 한번 더 추가
        for iii in item.split():
          if len(is_num.findall(j2hcj(h2j(iii))[0])) == 0:
            first_ii = j2hcj(h2j(iii))[0]
            dessert_name_dic[first_ii].append(iii)
    except:
      # 공백 문제인 item들 다시 봐보기
      print('{} 안넣었다.'.format(item.lstrip()))
      continue

for i in dessert_name_dic:                              #중복제거
  dessert_name_dic[i] = list(set(dessert_name_dic[i]))

remove_list=[]
for ii in dessert_name_dic:                             #한글자짜리 remove_list에 추가
  for dd in dessert_name_dic[ii]:
    if len(dd) == 1:
      remove_list.append(dd)

for i in dessert_name_dic:                              #한글자짜리 제거
  for remo in dessert_name_dic[i]:
    if remo in remove_list:
      dessert_name_dic[i].remove(remo)

for ii, vv in dessert_name_dic.items():
  print(ii,vv)

#저장
dps = pd.DataFrame.from_dict(dessert_name_dic, orient='index')
dps = dps.fillna("")
dps.to_csv('아뜰리에메뉴사전_real.csv', index=True)
dps
from google.colab import files
files.download('아뜰리에메뉴사전_real.csv')

#colab에 가져오기
from google.colab import files
uploaded = files.upload()